### ISSUE TITLE
Errors in IE11

### ISSUE THREAD

**Issue by jtlocsei** [dakra/mui-templates#1]
Opening the preview in IE11 I see the navigation but the main part of the screen is empty. Dev tools console shows the error "Object doesn't support property or method 'from'". I'm puzzled because  [the Material-UI docs claim that Material-UI supports IE11](https://material-ui.com/getting-started/supported-platforms/). Any idea how to get around this? I'm facing the same problem in my own app that uses Materal-UI. 

![image](https://user-images.githubusercontent.com/6704966/80293205-02c92b00-8790-11ea-8d02-4e6f5918f63c.png)

**Comment by dakra** [comment]
Thanks for reporting.
I don't have access to a Windows machine right now.
Maybe I'll try it in a VM or with Browserstack at some point but it's not very high on my todo list so don't wait for it. Especially as accoring to https://www.w3counter.com/globalstats.php IE11 has only 2.4% browser share.

If you find a solution I would be very happy to hear it and add it as well (if it's only a small shim).

**Comment by dakra** [comment]
I'm closing this at IE11 has dropped below 1% (0.7 according to w3counter) and I probably won't fix it any more.
Feel free to re-open or submit a fix if you find one.
Thanks.
